### ISSUE TITLE
缓存无效

### ISSUE THREAD

**Issue by hdtopku** [Ln-guolin/easy-cache-starter#1]
`pom.xml`中加入`easy-cache-starter`依赖以后，
```
@EasyLocalCache(namespace = "area", key = "'info:' + #code", timeout = 60 * 60 * 24)
```
缓存没效果，是我用错了吗？

**Comment by Ln-guolin** [comment]
需要注意的是，注解需要加在接口的实现方法上才会有效，如：
```java
class UserService {
        String query(String name);   
}

class UserServiceImpl UserService  {
        @EasyLocalCache(namespace = "test", key = "#name", timeout = 60 * 60 * 24)
        public String query(String name){
                  return "打印内容！！name="+ name + ",time=" + System.currentTimeMillis();
        }
}
```

你看看，如果还不行的话，你在工程里增加包扫描配置:"cn.soilove"

**Comment by hdtopku** [comment]
1、注解是放在实现类上面的
2、不行，加上包扫描配置：`@ComponentScan(basePackages = {"cn.soilove"})`
依然无法缓存

**Comment by Ln-guolin** [comment]
你应该还是工程配置的不对，
我给你提供一个最简单的案例，数据库已经配置了一个可用地址，你可以启动使用，从而找出你的代码问题。
启动后请求：`curl -H "Content-Type:application/json" -X GET "http://localhost:8080/test/query?name=zhangsan"`
案例下载地址：[https://rps.oss-cn-beijing.aliyuncs.com/demo.zip](https://rps.oss-cn-beijing.aliyuncs.com/demo.zip)
案例结构：
```java
demo
├── pom.xml
└── src
    ├── main
        ├── java
        │   └── com
        │       └── example
        │           └── demo
        │               ├── DemoApplication.java // 启动类
        │               ├── UserController.java
        │               ├── UserService.java
        │               └── UserServiceImpl.java
       └── resources
            └── application.properties
```

**Comment by hdtopku** [comment]
项目的子module的pom加入依赖，缓存不成功。后来在父pom加入依赖，缓存成功了。
此外，缓存只能作用在spring上下文Bean，不能作用于非spring管理的类，这点是否可以优化？

**Comment by hdtopku** [comment]
项目的子module的pom加入依赖，缓存不成功。后来在父pom加入依赖，缓存成功了。
此外，缓存只能作用在spring上下文Bean，不能作用于非spring管理的类，这点是否可以优化？
